
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter.tix import *
from tkinter import filedialog

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import tkinter as tk
def launch_lib_build():
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./assets")
    
    
    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)
    

    window.geometry("729x295")
    window.configure(bg = "#423C56")
    
    eg_results_dir = StringVar()
    out_dir = StringVar()
    error = StringVar()
    
    # eg_results_dir.set(r"D:\Manuscripts\2024_EndoGeniusDIA\fractionated_SL_data")
    # out_dir.set(r"C:\Users\lawashburn\Documents\EndoGeniusDistributions\version_assessment_output\EndoGenius_v1.1.0\sl_test2")
    error.set('0.02')
    
    def in_dir_path_get():
        in_dir_path_out = filedialog.askdirectory() 
        eg_results_dir.set(in_dir_path_out)
        
    def out_dir_path_get():
        out_dir_path_out = filedialog.askdirectory() 
        out_dir.set(out_dir_path_out)
    
    def launch_library_process():

        eg_results_dir_get = eg_results_dir.get()
        out_dir_get = out_dir.get()
        error_get = float(error.get())
        
        from sl_builder_driver import build_a_SL
        
        build_a_SL(eg_results_dir_get,out_dir_get,error_get)
        
        messagebox.showinfo("Process Complete", "The library has been built.")
    
    

    canvas = Canvas(
        window,
        bg = "#423C56",
        height = 295,
        width = 729,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )
    
    canvas.place(x = 0, y = 0)
    canvas.create_text(
        19.0,
        9.0,
        anchor="nw",
        text="Library Builder",
        fill="#FFFFFF",
        font=("Inter", 64 * -1)
    )
    
    canvas.create_rectangle(
        19.0,
        90.0,
        709.0,
        271.0,
        fill="#D9D9D9",
        outline="")
    
    canvas.create_text(
        26.0,
        106.0,
        anchor="nw",
        text="EndoGenius Results Directory",
        fill="#000000",
        font=("Inter", 16 * -1)
    )
    
    
    entry_1 = Entry(
        window,
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        textvariable = eg_results_dir
    )
    entry_1.place(
        x=274.0,
        y=106.0,
        width=340.0,
        height=28.0
    )
    
    button_image_1 = PhotoImage(
        file=relative_to_assets("lib_button_1.png"))
    button_1 = Button(
        canvas,
        text='Browse',
        borderwidth=0,
        highlightthickness=0,
        command=in_dir_path_get,
        relief="flat"
    )
    button_1.place(
        x=625.0,
        y=106.0,
        width=77.21710205078125,
        height=30.0
    )
    
    canvas.create_text(
        26.0,
        182.0,
        anchor="nw",
        text="Output Directory",
        fill="#000000",
        font=("Inter", 16 * -1)
    )
    
    
    entry_2 = Entry(
        window,
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        textvariable = out_dir
    )
    entry_2.place(
        x=274.0,
        y=182.0,
        width=340.0,
        height=28.0
    )
    
    canvas.create_text(
        26.0,
        144.0,
        anchor="nw",
        text="Fragment error threshold (Da)",
        fill="#000000",
        font=("Inter", 16 * -1)
    )
    
    
    entry_3 = Entry(
        window,
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0,
        textvariable = error
    )
    entry_3.place(
        x=274.0,
        y=144.0,
        width=69.0,
        height=28.0
    )
    

    button_2 = Button(
        canvas,
        text='Browse',
        borderwidth=0,
        highlightthickness=0,
        command=out_dir_path_get,
        relief="flat"
    )
    button_2.place(
        x=625.0,
        y=182.0,
        width=77.21710205078125,
        height=30.0
    )
    
    button_3 = Button(
        canvas,
        borderwidth=0,
        highlightthickness=0,
        text = 'Build Library',
        command=launch_library_process,
        relief="flat"
    )
    button_3.place(
        x=303.0,
        y=228.0,
        width=141.0,
        height=30.0
    )
    window.resizable(False, False)
    window.mainloop()
launch_lib_build()
