# -*- coding: utf-8 -*-
"""
Created on Thu Jul 25 14:47:27 2024

@author: lafields2
"""
from tkinter import Tk, Checkbutton, IntVar, Button
mod_window = Tk()

mod_window.geometry("500x580")
mod_window.configure(bg = "#D9D9D9")
mod_window.title('Modification selector')

amid_status = IntVar()
acet_term_status = IntVar()
acet_k_status = IntVar()
acet_s_status = IntVar()
acet_t_status = IntVar()
biotin_k_status = IntVar()
carb_term_status = IntVar()
carb_c_status = IntVar()
carb_d_status = IntVar()
carb_e_status = IntVar()
carb_h_status = IntVar()
carb_k_status = IntVar()
carboxy_d_status = IntVar()
carboxy_e_status = IntVar()
carboxy_k_status = IntVar()
carboxy_w_status = IntVar()
deamid_n_status = IntVar()
deamid_q_status = IntVar()
dehyd_d_status = IntVar()
dehyd_s_status = IntVar()
dehyd_t_status = IntVar()
dehyd_y_status = IntVar()
meth_k_status = IntVar()
meth_r_status = IntVar()
ox_m_status = IntVar()
sodi_d_status = IntVar()
sodi_e_status = IntVar()
plex12_nterm_status = IntVar()
plex12_k_status = IntVar()
pg_E_status = IntVar()
pg_q_status = IntVar()
sulfo_y_status = IntVar()
phospho_s_status = IntVar()
phospho_t_status = IntVar()
phospho_y_status = IntVar()

amid_check = Checkbutton(mod_window, text='Amidation (C-termini)', variable=amid_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
amid_check.place(x=5,y=5)
acet_term_check = Checkbutton(mod_window, text='Acetylation (N-termini)', variable=acet_term_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
acet_term_check.place(x=5,y=30)
acet_k_check = Checkbutton(mod_window, text='Acetylation (K)', variable=acet_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
acet_k_check.place(x=5,y=55)
acet_s_check = Checkbutton(mod_window, text='Acetylation (S)', variable=acet_s_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
acet_s_check.place(x=5,y=80)
acet_t_check = Checkbutton(mod_window, text='Acetylation (T)', variable=acet_t_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
acet_t_check.place(x=5,y=105)
biotin_k_check = Checkbutton(mod_window, text='Biotinylation (K)', variable=biotin_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
biotin_k_check.place(x=5,y=130)
carb_term_check = Checkbutton(mod_window, text='Carbamidomethylation (N-termini)', variable=carb_term_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_term_check.place(x=5,y=155)
carb_c_check = Checkbutton(mod_window, text='Carbamidomethylation (C)', variable=carb_c_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_c_check.place(x=5,y=180)
carb_d_check = Checkbutton(mod_window, text='Carbamidomethylation (D)', variable=carb_d_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_d_check.place(x=5,y=205)
carb_e_check = Checkbutton(mod_window, text='Carbamidomethylation (E)', variable=carb_e_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_e_check.place(x=5,y=230)
carb_h_check = Checkbutton(mod_window, text='Carbamidomethylation (H)', variable=carb_h_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_h_check.place(x=5,y=255)
carb_k_check = Checkbutton(mod_window, text='Carbamidomethylation (K)', variable=carb_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carb_k_check.place(x=5,y=280)
carboxy_d_check = Checkbutton(mod_window, text='Carboxylation (D)', variable=carboxy_d_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carboxy_d_check.place(x=5,y=305)
carboxy_e_check = Checkbutton(mod_window, text='Carboxylation (E)', variable=carboxy_e_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carboxy_e_check.place(x=5,y=330)
carboxy_k_check = Checkbutton(mod_window, text='Carboxylation (K)', variable=carboxy_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carboxy_k_check.place(x=5,y=355)
carboxy_w_check = Checkbutton(mod_window, text='Carboxylation (W)', variable=carboxy_w_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
carboxy_w_check.place(x=5,y=380)
deamid_n_check = Checkbutton(mod_window, text='Deamidation (N)', variable=deamid_n_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
deamid_n_check.place(x=5,y=405)
deamid_q_check = Checkbutton(mod_window, text='Deamidation (Q)', variable=deamid_q_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
deamid_q_check.place(x=5,y=430)
dehyd_d_check = Checkbutton(mod_window, text='Dehydration (D)', variable=dehyd_d_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
dehyd_d_check.place(x=5,y=455)
dehyd_s_check = Checkbutton(mod_window, text='Dehydration (S)', variable=dehyd_s_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
dehyd_s_check.place(x=300,y=5)
dehyd_t_check = Checkbutton(mod_window, text='Dehydration (T)', variable=dehyd_t_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
dehyd_t_check.place(x=300,y=30)
dehyd_y_check = Checkbutton(mod_window, text='Dehydration (Y)', variable=dehyd_y_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
dehyd_y_check.place(x=300,y=55)
meth_k_check = Checkbutton(mod_window, text='Methylation (K)', variable=meth_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
meth_k_check.place(x=300,y=80)
meth_r_check = Checkbutton(mod_window, text='Methylation (R)', variable=meth_r_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
meth_r_check.place(x=300,y=105)
ox_m_check = Checkbutton(mod_window, text='Oxidation (M)', variable=ox_m_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
ox_m_check.place(x=300,y=130)
sodi_d_check = Checkbutton(mod_window, text='Sodium adduct (D)', variable=sodi_d_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
sodi_d_check.place(x=300,y=155)
sodi_e_check = Checkbutton(mod_window, text='Sodium adduct (E)', variable=sodi_e_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
sodi_e_check.place(x=300,y=180)
plex12_nterm_check = Checkbutton(mod_window, text='12-plex DiLeu (N-terminal)', variable=plex12_nterm_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
plex12_nterm_check.place(x=300,y=205)
plex12_k_check = Checkbutton(mod_window, text='12-plex DiLeu (K)', variable=plex12_k_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
plex12_k_check.place(x=300,y=230)
pg_E_check = Checkbutton(mod_window, text='Pyro-Glu (E)', variable=pg_E_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
pg_E_check.place(x=300,y=255)
pg_q_check = Checkbutton(mod_window, text='Pyro-Glu (Q)', variable=pg_q_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
pg_q_check.place(x=300,y=280)
sulfo_y_check = Checkbutton(mod_window, text='Sulfation (Y)', variable=sulfo_y_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
sulfo_y_check.place(x=300,y=305)
phospho_s_check = Checkbutton(mod_window, text='Phosphorylation (S)', variable=phospho_s_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
phospho_s_check.place(x=300,y=330)
phospho_t_check = Checkbutton(mod_window, text='Phosphorylation (T)', variable=phospho_t_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
phospho_t_check.place(x=300,y=355)
phospho_y_check = Checkbutton(mod_window, text='Phosphorylation (Y)', variable=phospho_y_status,bg='#D9D9D9', onvalue = 1, offvalue = 0)
phospho_y_check.place(x=300,y=380)
ptm_button_1 = Button(mod_window,text='Submit',borderwidth=0,highlightthickness=0,relief="flat",command = mod_window.destroy)
ptm_button_1.place(x=200.0,y=500.0,width=78,height=30.0)

mod_window.mainloop()

